#!/bin/sh

# vaccine.js must NOT be in the source list.
source_dir='src'
app_name='backbone'

sources='
src/helpers.js
src/events.js
src/sync.js
src/history.js
src/model.js
src/collection.js
src/router.js
src/view.js
src/index.js
'

echo '//     Backbone.js 0.9.2

//     (c) 2010-2012 Jeremy Ashkenas, DocumentCloud Inc.
//     Backbone may be freely distributed under the MIT license.
//     For all details and documentation:
//     http://backbonejs.org
(function() {'

cat src/vaccine.js   # Output vaccine.js separately

for file in $sources
do
  name="$app_name/$(echo "$file" | sed -e "s#^$source_dir/##" -e 's/\.js//')"
  test "X$name" = "X$app_name/index" && name=$app_name
  echo "define('$name', function(require, exports, module) {"
  cat $file
  echo '});'
done

echo '}());'
